version: '3.3'
services: 



    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
            MYSQL_USER: vishvajit
            MYSQL_PASSWORD: vishvajit
        ports:
            - "3307:3306"

    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports:
        - "8000:8000"
        volumes:
        - .:/app
        - /tmp/app/mysqld:/run/mysqld
        depends_on:
        - db









        


