# Generated by Django 3.2.4 on 2021-06-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_choice_historicalchoice_historicalpoll_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpoll',
            name='question_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='question_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
