# Generated by Django 3.2.4 on 2021-06-11 08:56

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210610_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(default=api.models.Poll.get_id, on_delete=django.db.models.deletion.CASCADE, to='api.poll'),
        ),
        migrations.AlterField(
            model_name='historicalchoice',
            name='poll',
            field=models.ForeignKey(blank=True, db_constraint=False, default=api.models.Poll.get_id, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.poll'),
        ),
    ]
